language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services: mongodb

before_script:
  - printf "\n" | pecl install -f mongo-1.3.6
  - printf "\n" | pecl install yaml
  - composer --dev --prefer-source install

script: phpunit
